//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Worker {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Worker.IProcessor")]
    public interface IProcessor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessor/ProcessRequest", ReplyAction="http://tempuri.org/IProcessor/ProcessRequestResponse")]
        bool ProcessRequest(long requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessor/ProcessRequest", ReplyAction="http://tempuri.org/IProcessor/ProcessRequestResponse")]
        System.Threading.Tasks.Task<bool> ProcessRequestAsync(long requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessor/ProcessNewRequests", ReplyAction="http://tempuri.org/IProcessor/ProcessNewRequestsResponse")]
        bool ProcessNewRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessor/ProcessNewRequests", ReplyAction="http://tempuri.org/IProcessor/ProcessNewRequestsResponse")]
        System.Threading.Tasks.Task<bool> ProcessNewRequestsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcessorChannel : Tests.Worker.IProcessor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessorClient : System.ServiceModel.ClientBase<Tests.Worker.IProcessor>, Tests.Worker.IProcessor {
        
        public ProcessorClient() {
        }
        
        public ProcessorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ProcessRequest(long requestId) {
            return base.Channel.ProcessRequest(requestId);
        }
        
        public System.Threading.Tasks.Task<bool> ProcessRequestAsync(long requestId) {
            return base.Channel.ProcessRequestAsync(requestId);
        }
        
        public bool ProcessNewRequests() {
            return base.Channel.ProcessNewRequests();
        }
        
        public System.Threading.Tasks.Task<bool> ProcessNewRequestsAsync() {
            return base.Channel.ProcessNewRequestsAsync();
        }
    }
}
