//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nodule_wCI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commits
    {
        public Commits()
        {
            this.WebHookPostCommits = new HashSet<WebHookPostCommits>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public int ModifiedNo { get; set; }
        public int AddedNo { get; set; }
        public int DeletedNo { get; set; }
        public System.DateTime Date { get; set; }
        public string Url { get; set; }
        public string Message { get; set; }
    
        public virtual ICollection<WebHookPostCommits> WebHookPostCommits { get; set; }
    }
}
