//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nodule_wCI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebHookPostCommits
    {
        public long WebHookPostId { get; set; }
        public string CommitId { get; set; }
        public int Order { get; set; }
    
        public virtual Commits Commits { get; set; }
        public virtual WebHookPosts WebHookPosts { get; set; }
    }
}
