//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nodule_wCI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebHookPosts
    {
        public WebHookPosts()
        {
            this.WebHookPostCommits = new HashSet<WebHookPostCommits>();
        }
    
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string PostData { get; set; }
        public byte StatusId { get; set; }
        public string RepoUrl { get; set; }
        public string PullRequestReference { get; set; }
        public string Result { get; set; }
        public string Organization { get; set; }
    
        public virtual PostStatuses PostStatuses { get; set; }
        public virtual ICollection<WebHookPostCommits> WebHookPostCommits { get; set; }
    }
}
